import { UserDataType } from "../Data/UserData";
import {t} from 'i18next';
export const teyvat: UserDataType = {
  stations: [
    {
      stationId: 1,
      stationName: t('wang-feng-jiao-zhan'),
      position: [678, -52],
      shape: "cicle",
      lineIds: [3],
      tagDirection: 2,
    },
    {
      stationId: 2,
      stationName: t('zhai-xing-ya-zhan'),
      position: [645, 71],
      shape: "cicle",
      lineIds: [3],
    },
    {
      stationId: 3,
      stationName: t('qian-feng-shen-dian-zhan'),
      position: [640, 191],
      shape: "cicle",
      lineIds: [3],
    },
    {
      stationId: 4,
      stationName: "鹰翔海滩",
      position: [463, 418],
      shape: "cicle",
      lineIds: [2, 3, 8],
    },
    {
      stationId: 5,
      stationName: "达达乌帕谷",
      position: [573, 641],
      shape: "cicle",
      lineIds: [3],
    },
    {
      stationId: 6,
      stationName: "无相之雷",
      position: [740, 641],
      shape: "cicle",
      lineIds: [3],
    },
    {
      stationId: 7,
      stationName: "誓言岬机场",
      position: [813, 533],
      shape: "cicle",
      lineIds: [3],
    },
    {
      stationId: 8,
      stationName: "风起地站",
      position: [388, 318],
      shape: "cicle",
      lineIds: [1, 2],
    },
    {
      stationId: 9,
      stationName: "星落湖南",
      position: [458, 193],
      shape: "cicle",
      lineIds: [2],
    },
    {
      stationId: 10,
      stationName: "星落湖",
      position: [460, 86],
      shape: "cicle",
      lineIds: [2],
    },
    {
      stationId: 11,
      stationName: "无相之风站",
      position: [458, -64],
      shape: "cicle",
      lineIds: [2],
    },
    {
      stationId: 12,
      stationName: "望风开发区",
      position: [325, -102],
      shape: "cicle",
      lineIds: [2],
    },
    {
      stationId: 13,
      stationName: "风神像站",
      position: [245, 168],
      shape: "cicle",
      lineIds: [1],
    },
    {
      stationId: 14,
      stationName: "蒙德站",
      position: [320, 226],
      shape: "cicle",
      lineIds: [1],
    },
    {
      stationId: 15,
      stationName: "清泉镇",
      position: [270, 358],
      shape: "cicle",
      lineIds: [1],
    },
    {
      stationId: 16,
      stationName: "晨曦酒庄",
      position: [70, 428],
      shape: "cicle",
      lineIds: [1, 4, 8],
    },
    {
      stationId: 17,
      stationName: "奔狼岭",
      position: [-2, 336],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 18,
      stationName: "奔狼岭北",
      position: [3, 248],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 19,
      stationName: "风龙风景区",
      position: [-70, 151],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 20,
      stationName: "明冠峡",
      position: [15, 18],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 21,
      stationName: "风龙国际机场",
      position: [-87, -77],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 22,
      stationName: "雪山脚站",
      position: [83, 628],
      shape: "cicle",
      lineIds: [4],
      tagDirection: 2,
    },
    {
      stationId: 23,
      stationName: "无相之冰",
      position: [92, 748],
      shape: "cicle",
      lineIds: [4],
      tagDirection: 2,
    },
    {
      stationId: 24,
      stationName: "雪山顶站",
      position: [248, 748],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 25,
      stationName: "七天神像站",
      position: [338, 778],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 26,
      stationName: "雪山湖",
      position: [180, 851],
      shape: "cicle",
      lineIds: [4],
    },
    {
      stationId: 27,
      stationName: "地中之盐",
      position: [-35, 703],
      shape: "cicle",
      lineIds: [8],
    },
    {
      stationId: 28,
      stationName: "望舒客栈",
      position: [-230, 813],
      shape: "cicle",
      lineIds: [5, 8],
    },
    {
      stationId: 29,
      stationName: "石门",
      position: [-310, 568],
      shape: "cicle",
      lineIds: [5],
    },
    {
      stationId: 30,
      stationName: "轻策庄",
      position: [-452, 473],
      shape: "cicle",
      lineIds: [5],
    },
    {
      stationId: 31,
      stationName: "望舒南",
      position: [-240, 971],
      shape: "cicle",
      lineIds: [5],
    },
    {
      stationId: 32,
      stationName: "归离原",
      position: [-197, 1071],
      shape: "cicle",
      lineIds: [5],
    },
    {
      stationId: 33,
      stationName: "渌华池南",
      position: [-280, 1226],
      shape: "cicle",
      lineIds: [5],
    },
    {
      stationId: 34,
      stationName: "璃月港",
      position: [-285, 1451],
      shape: "cicle",
      lineIds: [5, 6],
    },
    {
      stationId: 35,
      stationName: "黄金屋",
      position: [-210, 1608],
      shape: "cicle",
      lineIds: [5, 7],
    },
    {
      stationId: 36,
      stationName: "青墟浦",
      position: [-605, 1601],
      shape: "cicle",
      lineIds: [7],
    },
    {
      stationId: 37,
      stationName: "灵矩国际机场",
      position: [-671, 1511],
      shape: "cicle",
      lineIds: [7, 11],
      tagDirection: 5,
    },
    {
      stationId: 38,
      stationName: "天衡山",
      position: [-362, 1351],
      shape: "cicle",
      lineIds: [6],
    },
    {
      stationId: 39,
      stationName: "遁玉陵",
      position: [-642, 1326],
      shape: "cicle",
      lineIds: [7],
    },
    {
      stationId: 40,
      stationName: "渌华池",
      position: [-437, 1158],
      shape: "cicle",
      lineIds: [6],
    },
    {
      stationId: 41,
      stationName: "翠玦坡",
      position: [-552, 1008],
      shape: "cicle",
      lineIds: [6],
    },
    {
      stationId: 42,
      stationName: "太山府",
      position: [-602, 946],
      shape: "cicle",
      lineIds: [6],
    },
    {
      stationId: 43,
      stationName: "机场东",
      position: [-525, 829],
      shape: "cicle",
      lineIds: [8],
    },
    {
      stationId: 44,
      stationName: "庆云国际机场",
      position: [-742, 828],
      shape: "cicle",
      lineIds: [6, 7, 8],
    },
    {
      stationId: 45,
      stationName: "奥藏山",
      position: [-805, 728],
      shape: "cicle",
      lineIds: [7],
    },
    {
      stationId: 46,
      stationName: "琥牢山",
      position: [-955, 903],
      shape: "cicle",
      lineIds: [7],
    },
    {
      stationId: 47,
      stationName: "伏龙树",
      position: [-857, 943],
      shape: "cicle",
      lineIds: [8],
    },
    {
      stationId: 48,
      stationName: "南天门",
      position: [-855, 1078],
      shape: "cicle",
      lineIds: [7],
    },
    {
      stationId: 49,
      stationName: "天遒谷",
      position: [-725, 1208],
      shape: "cicle",
      lineIds: [7],
    },
    {
      stationId: 50,
      stationName: "伏鳌谷",
      position: [-897, 1411],
      shape: "cicle",
      lineIds: [11, 12],
    },
    {
      stationId: 51,
      stationName: "香醉坡",
      position: [-1090, 1388],
      shape: "cicle",
      lineIds: [9, 11],
    },
    {
      stationId: 52,
      stationName: "无郁稠林",
      position: [-1090, 1076],
      shape: "cicle",
      lineIds: [9, 10],
    },
    {
      stationId: 53,
      stationName: "卡萨扎莱宫",
      position: [-1272, 1173],
      shape: "cicle",
      lineIds: [10],
    },
    {
      stationId: 54,
      stationName: "茸蕈窟",
      position: [-1405, 1271],
      shape: "cicle",
      lineIds: [10],
    },
    {
      stationId: 55,
      stationName: "须弥城",
      position: [-1360, 1388],
      shape: "cicle",
      lineIds: [10, 11],
    },
    {
      stationId: 56,
      stationName: "化城郭",
      position: [-1195, 1576],
      shape: "cicle",
      lineIds: [10, 12],
    },
    {
      stationId: 57,
      stationName: "丹砂崖",
      position: [-1037, 1491],
      shape: "cicle",
      lineIds: [9, 12],
    },
    {
      stationId: 58,
      stationName: "降诸魔山东",
      position: [-1067, 1791],
      shape: "cicle",
      lineIds: [9],
      tagDirection: 2,
    },
    {
      stationId: 59,
      stationName: "降诸魔山",
      position: [-1177, 1933],
      shape: "cicle",
      lineIds: [9],
      tagDirection: 3,
    },
    {
      stationId: 60,
      stationName: "奥摩斯港北",
      position: [-1310, 1931],
      shape: "cicle",
      lineIds: [9, 10],
      tagDirection: 7,
    },
    {
      stationId: 61,
      stationName: "奥摩斯港",
      position: [-1247, 2116],
      shape: "cicle",
      lineIds: [10],
    },
    {
      stationId: 62,
      stationName: "维摩庄",
      position: [-1255, 1701],
      shape: "cicle",
      lineIds: [10],
      tagDirection: 3,
    },
    {
      stationId: 63,
      stationName: "禅那园",
      position: [-1522, 1681],
      shape: "cicle",
      lineIds: [11, 12],
    },
    {
      stationId: 64,
      stationName: "谒颂幽境",
      position: [-1695, 1681],
      shape: "cicle",
      lineIds: [12],
    },
    {
      stationId: 65,
      stationName: "桓那兰那",
      position: [-1865, 1493],
      shape: "cicle",
      lineIds: [12],
    },
    {
      stationId: 66,
      stationName: "五绿洲",
      position: [-2215, 1326],
      shape: "cicle",
      lineIds: [12],
    },
    {
      stationId: 67,
      stationName: "喀万驿",
      position: [-1812, 1908],
      shape: "cicle",
      lineIds: [11],
    },
    {
      stationId: 68,
      stationName: "水天丛林",
      position: [-1482, 1931],
      shape: "cicle",
      lineIds: [9],
    },
    {
      stationId: 69,
      stationName: "荼诃之座",
      position: [-1737, 1998],
      shape: "cicle",
      lineIds: [9],
    },
    {
      stationId: 70,
      stationName: "阿如村",
      position: [-1917, 2093],
      shape: "cicle",
      lineIds: [9, 11],
    },
    {
      stationId: 71,
      stationName: "圣显厅",
      position: [-2077, 1883],
      shape: "cicle",
      lineIds: [9],
    },
    {
      stationId: 72,
      stationName: "活力之家",
      position: [-1997, 2211],
      shape: "cicle",
      lineIds: [11],
    },
    {
      stationId: 73,
      stationName: "丰饶绿洲",
      position: [-2212, 2316],
      shape: "cicle",
      lineIds: [11],
    },
    {
      stationId: 74,
      stationName: "赤王陵",
      position: [-2470, 2316],
      shape: "cicle",
      lineIds: [11],
    },
  ].reduce((map, cur) => {
    map.set(cur.stationId, cur);
    return map;
  }, new Map()),
  lines: [
    {
      lineId: 1,
      lineName: "1号线",
      color: "#EA0B2A",
      stationIds: [13, 14, 8, 15, 16],
      sign: "1",
      order: 1,
      bendFirst: [true, true, true, true, true],
    },
    {
      lineId: 2,
      lineName: "2号线",
      color: "#94D40B",
      stationIds: [12, 11, 10, 9, 8, 4],
      sign: "2",
      order: 2,
      bendFirst: [false, true, true, true, true, true],
    },
    {
      lineId: 3,
      lineName: "3号线",
      color: "#F8D000",
      stationIds: [1, 2, 3, 4, 5, 6, 7],
      sign: "3",
      order: 3,
      bendFirst: [true, true, true, false, true, true, true],
    },
    {
      lineId: 4,
      lineName: "4号线",
      color: "#60269E",
      stationIds: [21, 20, 19, 18, 17, 16, 22, 23, 26, 25, 24],
      sign: "4",
      order: 4,
      bendFirst: [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
      ],
    },
    {
      lineId: 5,
      lineName: "5号线",
      color: "#934C9A",
      stationIds: [30, 29, 28, 31, 32, 33, 34, 35],
      sign: "5",
      order: 5,
      bendFirst: [true, true, true, true, true, true, true, true],
    },
    {
      lineId: 6,
      lineName: "6号线",
      color: "#D80169",
      stationIds: [44, 42, 41, 40, 38, 34],
      sign: "6",
      order: 6,
      bendFirst: [false, true, true, true, false, true],
    },
    {
      lineId: 7,
      lineName: "7号线",
      color: "#FE6B01",
      stationIds: [35, 36, 37, 39, 49, 48, 46, 45, 44],
      sign: "7",
      order: 7,
      bendFirst: [true, true, true, false, true, true, false, true, true],
    },
    {
      lineId: 8,
      lineName: "8号线",
      color: "#00A0E8",
      stationIds: [47, 44, 43, 28, 27, 16, 4],
      sign: "8",
      order: 8,
      bendFirst: [true, true, false, false, false, false, true],
    },
    {
      lineId: 9,
      lineName: "须弥2号线",
      color: "#385f88",
      stationIds: [52, 51, 57, 58, 59, 60, 68, 69, 70, 71],
      sign: "2",
      order: 9,
      bendFirst: [true, true, true, false, true, true, true, true, true, true],
    },
    {
      lineId: 10,
      lineName: "须弥1号线",
      color: "#e8c148",
      stationIds: [52, 53, 54, 55, 56, 62, 60, 61],
      sign: "1",
      order: 10,
      bendFirst: [false, false, false, true, false, true, true, true],
    },
    {
      lineId: 11,
      lineName: "须弥3号线",
      color: "#dd8d4e",
      stationIds: [37, 50, 51, 55, 63, 67, 70, 72, 73, 74],
      sign: "3",
      order: 11,
      bendFirst: [false, true, true, true, true, true, false, true, true, true],
    },
    {
      lineId: 12,
      lineName: "须弥4号线",
      color: "#35743c",
      stationIds: [50, 57, 56, 63, 64, 65, 66],
      sign: "4",
      order: 12,
      bendFirst: [true, true, true, true, true, true, true],
    },
  ].reduce((map, cur) => {
    map.set(cur.lineId, cur);
    return map;
  }, new Map()),
  title: t('teyvat'),
  backgroundColor: '#ffffff',
};
